# Generated by Django 5.2.3 on 2025-06-12 05:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TashanVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='tashans/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('SH', 'SHERNI'), ('BN', 'BINDAAS'), ('NV', 'NAVAV'), ('DB', 'DABANG'), ('TR', 'TEWAR')], max_length=2)),
            ],
        ),
    ]
